apiVersion : kustomize.config.k8s.io/v1beta1
kind: kustomization 

namespace:  app-dev 

resources:
  - ../../base

patchesStrategicMerge:
 - deploy-dev.yaml
 - svc-dev.yaml
 - ingress-dev.yaml

commonLabels:
  environment: dev
  app: my-node-app